'use strict';

/**
 * tests/services/opsBriefingCountInvariant.test.js — OPS-BRIEF-1A.
 *
 * Owner-approved 2026-09-06.
 *
 * Root cause the fix addresses:
 *   src/services/operationsBriefing.js:summarizeOrders() previously
 *   counted `auto_generated=true AND status!=done` team_tasks via
 *   `.limit(500)` + in-memory `excRows.length`. Once open auto-exception
 *   cards exceeded 500 the metric saturated at exactly 500 while the UI
 *   label read "자동 예외 (전체)". Production observed: 993 real vs 500
 *   shown, 555 SKU_MATCH_FAILED real vs 296 shown (undercount from an
 *   arbitrary 500-row slice that happened to include only 296 matches).
 *
 * Invariant under test (owner rule §7 + §20):
 *   briefing.exception_count       == exact server-side count(auto_generated=true AND status!=done)
 *   briefing.sku_match_failed      == exact server-side count(... AND exception_type='SKU_MATCH_FAILED')
 *   briefing.sku_match_failed      == filtered detail array length from
 *                                     GET /api/tasks?autoGenerated=true&exceptionType=SKU_MATCH_FAILED&status=open
 *                                     (repo owner path)
 *
 * UNKNOWN ≠ ZERO (owner rule §5):
 *   If the count query fails, the metric MUST remain null (rendered as
 *   '-' in UI) — never silently collapse to 0.
 *
 * Non-scope:
 *   No production code was modified for testability. `src/api/ebayAPI.js`,
 *   tracking observer, scheduler code, and orderSync.js are untouched.
 *   R2-SHIP-6F1C-D deployment is independent.
 */

const test   = require('node:test');
const assert = require('node:assert/strict');
const fs     = require('fs');
const path   = require('path');

const SUPABASE_PATH   = require.resolve('../../src/db/supabaseClient');
const OPS_BRIEF_PATH  = require.resolve('../../src/services/operationsBriefing');
const REPO_PATH       = require.resolve('../../src/db/teamTaskRepository');

let _orig = null;
function saveOriginals() {
  _orig = {
    supabase: require.cache[SUPABASE_PATH],
    ops:      require.cache[OPS_BRIEF_PATH],
    repo:     require.cache[REPO_PATH],
  };
}
function restoreOriginals() {
  const restore = (p, orig) => {
    if (orig) require.cache[p] = orig;
    else      delete require.cache[p];
  };
  if (!_orig) return;
  restore(SUPABASE_PATH,  _orig.supabase);
  restore(OPS_BRIEF_PATH, _orig.ops);
  restore(REPO_PATH,      _orig.repo);
  _orig = null;
}

// ─────────────────────────────────────────────────────────────────────────
// Fake Supabase client — models the exact query shapes the code uses.
// ─────────────────────────────────────────────────────────────────────────
//
// Supported query shapes (only what our SUT calls):
//   from(table).select(cols, opts?).eq(k,v).neq(k,v)...  → thenable → {data,error}
//   from(table).select('id', { count:'exact', head:true }).eq/neq…  → thenable → {count,error}
//   from(table).select('*').eq/neq/in/or.order().limit().range()    → matches listTasks + summarizeOrders
//
// The stub applies filters conjunctively over a plain in-memory array of rows.
function makeFakeDb(tables) {
  // tables: { [tableName]: Row[] }
  function query(tableName) {
    const rows = Array.isArray(tables[tableName]) ? tables[tableName].slice() : [];
    const state = {
      filters: [],      // predicates: (row) => boolean
      countMode: null,  // 'exact' | null
      headOnly: false,
      selectCols: null,
      limitN: null,
      orderKey: null,
      orderAsc: true,
    };
    const applyFilters = () => rows.filter(r => state.filters.every(p => p(r)));

    const q = {
      select(cols, opts) {
        state.selectCols = cols;
        if (opts && opts.count) state.countMode = opts.count;
        if (opts && opts.head)  state.headOnly  = true;
        return q;
      },
      eq(k, v)  { state.filters.push(r => r[k] === v); return q; },
      neq(k, v) { state.filters.push(r => r[k] !== v); return q; },
      in(k, arr){ state.filters.push(r => arr.includes(r[k])); return q; },
      //   OPS-BRIEF-1B · TODAY_NEW 예측: oms_orders.ordered_at >= todayStartIso.
      //   Predicate ISO 문자열 비교 — timestamptz 저장값과 동일 lexical 정렬 (both UTC Z).
      gte(k, v) { state.filters.push(r => r[k] != null && r[k] >= v); return q; },
      lte(k, v) { state.filters.push(r => r[k] != null && r[k] <= v); return q; },
      gt(k, v)  { state.filters.push(r => r[k] != null && r[k] >  v); return q; },
      lt(k, v)  { state.filters.push(r => r[k] != null && r[k] <  v); return q; },
      or(_expr) { /* summarizeOrders 등에서 사용 X — 미구현 pass-through */ return q; },
      order(k, opts) { state.orderKey = k; state.orderAsc = !(opts && opts.ascending === false); return q; },
      limit(n)  { state.limitN = n; return q; },
      range()   { return q; },
      // await 시 발화 — 결과 형태는 select 호출 시 옵션에 따라 결정.
      then(onFulfilled, onRejected) {
        try {
          const filtered = applyFilters();
          let out;
          if (state.countMode === 'exact' && state.headOnly) {
            // count-only response
            out = { data: null, count: filtered.length, error: null };
          } else {
            let ordered = filtered;
            if (state.orderKey) {
              ordered = filtered.slice().sort((a, b) => {
                const av = a[state.orderKey], bv = b[state.orderKey];
                if (av === bv) return 0;
                return (av < bv ? -1 : 1) * (state.orderAsc ? 1 : -1);
              });
            }
            const limited = state.limitN != null ? ordered.slice(0, state.limitN) : ordered;
            out = { data: limited, count: state.countMode === 'exact' ? filtered.length : null, error: null };
          }
          return Promise.resolve(out).then(onFulfilled, onRejected);
        } catch (e) {
          return Promise.reject(e).catch(onRejected);
        }
      },
    };
    return q;
  }

  return {
    from(tableName) {
      // Support both the direct-then and chainable await patterns.
      const q = query(tableName);
      return q;
    },
  };
}

function installFakeSupabase(fakeDb) {
  require.cache[SUPABASE_PATH] = {
    id: SUPABASE_PATH, filename: SUPABASE_PATH, loaded: true,
    exports: {
      getClient: () => fakeDb,
      isSupabaseEnabled: () => true,
      getDbSource: () => 'test',
      isDualWrite: () => false,
      withReadCache: async (fn) => ({ value: await fn(), stats: {} }),
    },
  };
  // Force operationsBriefing + repo to re-resolve the fake supabaseClient.
  delete require.cache[OPS_BRIEF_PATH];
  delete require.cache[REPO_PATH];
}

// Fixture builders ────────────────────────────────────────────────────────
function mkAutoExc(id, exceptionType, status = 'pending') {
  return {
    id,
    auto_generated: true,
    exception_type: exceptionType,
    status,
    created_at: new Date(Date.now() - id * 60_000).toISOString(),
    // populated to be listTasks-compatible
    title: `auto card #${id}`,
    priority: 'normal',
    created_by: null,
    completed_at: null,
    completion_note: null,
    memo: null,
    due_date: null,
    assignee_id: null,
    assignee_scope: 'operators',
    severity: 'medium',
    dedupe_key: `dedupe:${exceptionType}:${id}`,
    context: null,
    related_sku_id: null,
    related_order_id: null,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// STRUCTURAL — prove the LIMIT-500 saturation pattern is gone.
// ─────────────────────────────────────────────────────────────────────────

test('STRUCT-1 · summarizeOrders no longer uses .limit(500) on team_tasks', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  // Isolate the summarizeOrders function body (up to the next `async function` decl).
  const start = src.indexOf('async function summarizeOrders');
  assert.ok(start > 0, 'summarizeOrders must exist');
  const rest = src.slice(start);
  const end = rest.indexOf('\nasync function ');
  const body = end > 0 ? rest.slice(0, end) : rest;

  // NO in-memory team_tasks limit-then-length saturation.
  assert.equal(
    /from\(\s*['"]team_tasks['"]\s*\)[\s\S]{0,400}\.limit\(\s*500\s*\)/.test(body),
    false,
    'team_tasks LIMIT 500 saturation pattern must be removed from summarizeOrders'
  );

  // Exact-count contract MUST be present.
  assert.ok(
    /count:\s*['"]exact['"][\s\S]{0,50}head:\s*true/.test(body)
    || /head:\s*true[\s\S]{0,50}count:\s*['"]exact['"]/.test(body),
    'summarizeOrders must use { count:"exact", head:true } for team_tasks counts'
  );
});

test('STRUCT-2 · summarizeOrders preserves both auto-exception predicates', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  // .eq('auto_generated', true) AND .neq('status', 'done') both present.
  assert.ok(/\.eq\(\s*['"]auto_generated['"]\s*,\s*true\s*\)/.test(src));
  assert.ok(/\.neq\(\s*['"]status['"]\s*,\s*['"]done['"]\s*\)/.test(src));
  // SKU_MATCH_FAILED equality still expressed literally.
  assert.ok(/['"]SKU_MATCH_FAILED['"]/.test(src));
});

test('STRUCT-3 · UNKNOWN != ZERO — nulls not zero on catch path', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  const start = src.indexOf('async function summarizeOrders');
  const body  = src.slice(start, src.indexOf('\nasync function ', start));
  // Neither counter is initialised to 0 anymore.
  assert.equal(/let\s+exception_count\s*=\s*0\b/.test(body), false);
  assert.equal(/let\s+sku_match_failed\s*=\s*0\b/.test(body), false);
  // Both start life as null (UNKNOWN).
  assert.ok(/let\s+exception_count\s*=\s*null\b/.test(body));
  assert.ok(/let\s+sku_match_failed\s*=\s*null\b/.test(body));
});

test('STRUCT-4 · repo listTasks accepts exceptionType + status=open', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/db/teamTaskRepository.js'), 'utf8'
  );
  assert.ok(/function\s+listTasks\s*\(\s*\{[^}]*exceptionType[^}]*\}/.test(src),
    'listTasks signature must include exceptionType');
  assert.ok(/status\s*===\s*['"]open['"]/.test(src),
    'listTasks must branch on status === "open"');
  assert.ok(/\.eq\(\s*['"]exception_type['"]\s*,\s*exceptionType\s*\)/.test(src),
    'listTasks must forward exceptionType to a server-side .eq predicate');
});

test('STRUCT-5 · /api/tasks route whitelists exceptionType', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/web/routes/tasks.js'), 'utf8'
  );
  assert.ok(/ALLOWED_EXCEPTION_TYPES\s*=\s*\[\s*['"]SKU_MATCH_FAILED['"]\s*\]/.test(src),
    'tasks.js must declare a whitelist containing SKU_MATCH_FAILED');
  assert.ok(/invalid\s+exceptionType/i.test(src),
    'tasks.js must reject unsupported exceptionType with a 400 error message');
});

// ─────────────────────────────────────────────────────────────────────────
// BEHAVIORAL — exact counts + count = detail invariant.
// ─────────────────────────────────────────────────────────────────────────

test.beforeEach(saveOriginals);
test.afterEach(restoreOriginals);

test('BRIEF-T1 · >500 open auto exceptions counted exactly (505, not 500)', async () => {
  const rows = [];
  for (let i = 1; i <= 505; i++) rows.push(mkAutoExc(i, 'AUTOMATION_FAILED'));
  const db = makeFakeDb({
    wms_orders: [],
    team_tasks: rows,
  });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count, 505, 'must be exact 505, not saturated 500');
  assert.equal(b.orders.sku_match_failed, 0, 'no SKU_MATCH_FAILED in fixture → 0');
});

test('BRIEF-T2 · mixed 993 open · 555 SKU_MATCH_FAILED · reproduces production truth', async () => {
  const rows = [];
  let id = 1;
  for (let i = 0; i < 555; i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  for (let i = 0; i < 438; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  // 993 total, all pending
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  993, 'exact 993, not saturated 500');
  assert.equal(b.orders.sku_match_failed, 555, 'exact 555, not undercounted 296');
});

test('BRIEF-T3 · done SKU_MATCH_FAILED cards excluded from both open counts', async () => {
  const rows = [
    mkAutoExc(1, 'SKU_MATCH_FAILED', 'pending'),
    mkAutoExc(2, 'SKU_MATCH_FAILED', 'in_progress'),
    mkAutoExc(3, 'SKU_MATCH_FAILED', 'done'),       // must be excluded
    mkAutoExc(4, 'AUTOMATION_FAILED', 'done'),      // must be excluded
    mkAutoExc(5, 'AUTOMATION_FAILED', 'pending'),
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  3, 'done cards excluded → 3 open');
  assert.equal(b.orders.sku_match_failed, 2, 'done SKU cards excluded → 2 open');
});

test('BRIEF-T4/T7 · detail total = briefing sku_match_failed · count == detail', async () => {
  // Same 993/555 fixture — exercise both the service count and the repo owner-path
  // list under the same DB state.
  const rows = [];
  let id = 1;
  for (let i = 0; i < 555; i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  for (let i = 0; i < 438; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);

  const opsBrief = require(OPS_BRIEF_PATH);
  const repo     = require(REPO_PATH);

  const b = await opsBrief.getTodayBriefing();
  const detail = await repo.listTasks({
    user:          { id: 999, isAdmin: true },
    autoGenerated: 'true',
    exceptionType: 'SKU_MATCH_FAILED',
    status:        'open',
  });
  assert.equal(detail.length, b.orders.sku_match_failed,
    'briefing.sku_match_failed must equal filtered detail array length (count = detail invariant)');
  assert.equal(detail.length, 555, 'detail must return the full filtered set — not a page slice');
});

test('BRIEF-T5 · repo listTasks with unsupported exceptionType is caller-controlled', async () => {
  // The whitelist enforcement lives in the route layer (see STRUCT-5). The repo
  // itself must forward whatever value the caller passes as a .eq filter — this
  // preserves the count = detail contract without hard-coding the enum inside the
  // repo (extensible when new values are approved).
  const rows = [
    mkAutoExc(1, 'SKU_MATCH_FAILED'),
    mkAutoExc(2, 'NOT_ON_WHITELIST'),
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);
  const repo = require(REPO_PATH);
  const detail = await repo.listTasks({
    user: { id: 1, isAdmin: true }, autoGenerated: 'true', exceptionType: 'NOT_ON_WHITELIST',
  });
  assert.equal(detail.length, 1, 'repo forwards filter server-side; whitelist enforced upstream');
});

test('BRIEF-T6 · exceptionType filter runs server-side (not client-slice)', async () => {
  // 600 rows total; 55 match SKU_MATCH_FAILED. If filter ran client-side over a
  // capped 500-row slice, matches would be at most 55 * (500/600) ~ 45 on average
  // (or exactly 55 if the slice ordering happened to include all — the flaky
  // saturation bug we're removing). Server-side filter always returns 55.
  const rows = [];
  let id = 1;
  for (let i = 0; i < 545; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  for (let i = 0; i < 55;  i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);
  const repo = require(REPO_PATH);
  const detail = await repo.listTasks({
    user: { id: 1, isAdmin: true }, autoGenerated: 'true',
    exceptionType: 'SKU_MATCH_FAILED', status: 'open',
  });
  assert.equal(detail.length, 55, 'server-side filter reaches every matching row regardless of physical position');
});

test('BRIEF-UNKNOWN · count query failure leaves nulls, not zero', async () => {
  const rows = [mkAutoExc(1, 'SKU_MATCH_FAILED')];
  // Poison team_tasks count queries to force the catch branch.
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'team_tasks') return orig(name);
    // Return a chainable stub that rejects on await.
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      order() { return chain; }, limit() { return chain; },
      then(_ok, err) { return Promise.reject(new Error('simulated count failure')).catch(err); },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  null, 'UNKNOWN != ZERO — must stay null');
  assert.equal(b.orders.sku_match_failed, null, 'UNKNOWN != ZERO — must stay null');
});

// ─────────────────────────────────────────────────────────────────────────
// Frontend structural tests (no jsdom infra in this repo) — cover T8..T12.
// ─────────────────────────────────────────────────────────────────────────

test('BRIEF-T8 · opsBriefing.js — SKU 매칭 실패 row carries drill target', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  // The literal tuple slot for SKU_MATCH_FAILED must reference the drill object.
  assert.ok(/SKU 매칭 실패[\s\S]{0,300}skuDrill/.test(src),
    'SKU 매칭 실패 items entry must attach the skuDrill target');
  // Drill target destination + params must match the deep-link contract.
  assert.ok(/exceptionType=SKU_MATCH_FAILED/.test(src));
  assert.ok(/status=open/.test(src));
  assert.ok(/page:\s*['"]exception-tasks['"]/.test(src));
});

test('BRIEF-T9 · opsBriefing.js — non-positive value renders as static row', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  // Guard: link renders ONLY when drill && numeric value > 0.
  assert.ok(/isNumericPositive[\s\S]{0,100}drill\s*&&\s*isNumericPositive/.test(src)
         || /drill\s*&&\s*isNumericPositive/.test(src),
    'row link must guard on (drill && numeric value > 0) — zero / null renders as non-clickable');
});

test('BRIEF-T10 · exceptionFilter.js — first fetch sends URL exceptionType', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  // URL parse present, whitelist enforced, and refresh() sends exceptionType server-side.
  assert.ok(/URL_ALLOWED_EXCEPTION_TYPES[\s\S]{0,80}SKU_MATCH_FAILED/.test(src),
    'exceptionFilter must declare a URL whitelist');
  assert.ok(/URLSearchParams\(location\.search\)/.test(src),
    'exceptionFilter must parse location.search');
  assert.ok(/params\.set\(\s*['"]exceptionType['"]\s*,\s*urlExceptionType\s*\)/.test(src),
    'refresh() must forward urlExceptionType to the server');
});

test('BRIEF-T11 · exceptionFilter.js — status=open forwarded to server', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  assert.ok(/urlStatusOpen[\s\S]{0,120}params\.set\(\s*['"]status['"]\s*,\s*['"]open['"]\s*\)/.test(src),
    'urlStatusOpen must translate to server-side status=open on refresh()');
});

// ─────────────────────────────────────────────────────────────────────────
// OPS-BRIEF-1A-H1 · UNKNOWN != ZERO in the 09:00 notification body.
// ─────────────────────────────────────────────────────────────────────────
//
// Before H1, buildBriefingNotification used truthiness (`if (o.exception_count)`)
// which suppresses `null` and `0` identically. That silently lost UNKNOWN
// semantics — a failed count query looked exactly like "no issues today".
//
// After H1:
//   known positive  → segment with the actual count (unchanged contract)
//   known zero      → suppressed (existing quiet-body contract)
//   unknown (null)  → explicit "확인 실패" segment · never masquerades as zero
// buildRecommendations also emits an explicit UNKNOWN recommendation so the
// "정상 운영 중입니다" fallback line cannot fire while a count is unknown.

function fakeBriefing(orders = {}) {
  // Purchase / safety / tasks default to KNOWN-zero so the fallback line
  // is the only recommendation candidate absent any auto-exception input.
  return {
    date: '2026-09-06',
    orders: { total_today: 0, pending: 0, exception_count: null, sku_match_failed: null, ...orders },
    tasks: { open: 0, urgent: 0, overdue: 0, completed_today: 0 },
    purchase_requests: { pending: 0, approved_today: 0, ordered_today: 0 },
    safety: { failed_runs_today: 0, rollbackable_runs: 0, rolled_back_today: 0 },
    recommendations: [],
  };
}

test('BRIEF-H1 · exception_count = 0 → known zero suppressed per contract', () => {
  // Fresh load to shake off any test-side stubs from earlier suites.
  restoreOriginals();
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = fakeBriefing({ exception_count: 0, sku_match_failed: 0 });
  const n = opsBrief.buildBriefingNotification(b);
  assert.equal(/자동 예외/.test(n.body), false,
    'known-zero exception_count MUST be suppressed (existing quiet-body contract)');
  assert.equal(/확인 실패/.test(n.body), false,
    'known zero MUST NOT masquerade as UNKNOWN');
});

test('BRIEF-H2 · exception_count = null → visible UNKNOWN · distinct from zero', () => {
  restoreOriginals();
  const opsBrief = require(OPS_BRIEF_PATH);
  const bNull = fakeBriefing({ exception_count: null, sku_match_failed: null });
  const bZero = fakeBriefing({ exception_count: 0, sku_match_failed: 0 });
  const nNull = opsBrief.buildBriefingNotification(bNull);
  const nZero = opsBrief.buildBriefingNotification(bZero);
  assert.ok(/자동 예외 확인 실패/.test(nNull.body),
    'null exception_count MUST produce an explicit 확인 실패 segment');
  assert.notEqual(nNull.body, nZero.body,
    'UNKNOWN and KNOWN-zero notifications MUST be distinguishable to the owner');
});

test('BRIEF-H3 · sku_match_failed = 0 → known zero suppressed per contract', () => {
  restoreOriginals();
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = fakeBriefing({ exception_count: 0, sku_match_failed: 0 });
  const n = opsBrief.buildBriefingNotification(b);
  assert.equal(/SKU 매칭 실패/.test(n.body), false,
    'known-zero sku_match_failed MUST be suppressed (contract: recommendation carries positives, body stays quiet)');
});

test('BRIEF-H4 · sku_match_failed = null → visible UNKNOWN in body', () => {
  restoreOriginals();
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = fakeBriefing({ exception_count: 0, sku_match_failed: null });
  const n = opsBrief.buildBriefingNotification(b);
  assert.ok(/SKU 매칭 실패 확인 실패/.test(n.body),
    'null sku_match_failed MUST produce an explicit 확인 실패 segment');
});

test('BRIEF-H5 · positive counts render exact numbers · UNKNOWN wording absent', () => {
  restoreOriginals();
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = fakeBriefing({ exception_count: 993, sku_match_failed: 555 });
  const n = opsBrief.buildBriefingNotification(b);
  assert.ok(/자동 예외 993건/.test(n.body),
    'positive exception_count must render the actual number');
  // sku_match_failed positive is intentionally NOT in the body segments — the
  // recommendations layer surfaces it. Confirm that the H1 UNKNOWN branch does
  // not fire on known-positive.
  assert.equal(/자동 예외 확인 실패/.test(n.body), false);
  assert.equal(/SKU 매칭 실패 확인 실패/.test(n.body), false);
});

test('BRIEF-H6 · summarizeOrders count failure → notification UNKNOWN · never 0', async () => {
  // End-to-end: force team_tasks count queries to reject; verify service returns
  // nulls AND the notification body surfaces UNKNOWN wording (not "정상 운영").
  const db = makeFakeDb({ wms_orders: [], team_tasks: [] });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'team_tasks') return orig(name);
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      order() { return chain; }, limit() { return chain; },
      then(_ok, err) { return Promise.reject(new Error('simulated count failure')).catch(err); },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  null, 'service must expose null on count failure');
  assert.equal(b.orders.sku_match_failed, null, 'service must expose null on count failure');

  const n = opsBrief.buildBriefingNotification(b);
  assert.ok(/확인 실패/.test(n.body),
    'notification body MUST carry an explicit 확인 실패 marker on count failure');
  assert.equal(/정상 운영/.test(n.body), false,
    '"정상 운영 중입니다" MUST NOT appear when a count is unknown');
});

test('BRIEF-H7 · buildRecommendations emits UNKNOWN recommendation when a count is null', async () => {
  // Poison team_tasks count queries → summarizeOrders yields
  // exception_count=null / sku_match_failed=null. getTodayBriefing then invokes
  // buildRecommendations, which MUST emit an explicit UNKNOWN recommendation and
  // MUST NOT emit the "정상 운영 중입니다" fallback (which used to silently fire
  // whenever every positive branch failed — treating UNKNOWN as calm).
  const db = makeFakeDb({ wms_orders: [], team_tasks: [] });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'team_tasks') return orig(name);
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      order() { return chain; }, limit() { return chain; },
      then(_ok, err) { return Promise.reject(new Error('simulated count failure')).catch(err); },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();

  assert.ok(Array.isArray(b.recommendations), 'recommendations must be present');
  const rec = b.recommendations.join('\n');
  assert.ok(/확인 실패/.test(rec),
    'recommendations MUST include an explicit UNKNOWN recommendation when a count is null');
  assert.equal(/정상 운영/.test(rec), false,
    '"정상 운영 중입니다" MUST NOT appear in recommendations when a count is UNKNOWN');
});

test('BRIEF-T12 · drill-down surface uses GET only — no mutation added', () => {
  const briefSrc = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  const filterSrc = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  // The new drill click path uses history.pushState + showPage. No fetch() with a
  // non-GET method was added by 1A.
  const drillBlock = briefSrc.slice(briefSrc.indexOf('ob-drill'));
  assert.equal(/method:\s*['"](POST|PATCH|PUT|DELETE)['"]/.test(drillBlock), false,
    'briefing drill wiring must be GET-only');
  // The URL-init path in exceptionFilter must not add any new mutation call —
  // PATCH /api/tasks/:id (완료 처리) already exists and is UNCHANGED.
  const patchCount = (filterSrc.match(/method:\s*['"]PATCH['"]/g) || []).length;
  assert.equal(patchCount, 1, 'exceptionFilter should still have exactly 1 PATCH call (existing 완료 처리 workflow — untouched)');
});

// ─────────────────────────────────────────────────────────────────────────
// OPS-BRIEF-1B · Canonical OMS briefing counts + card split + KST + UNKNOWN.
// ─────────────────────────────────────────────────────────────────────────
//
// Migrates 오늘 신규 주문 / 미처리 from legacy wms_orders (production 1 row,
// mock-only sink) to canonical oms_orders (production 1823 rows, active
// ingestion from eBay + Shopify + deferred channels). Also fixes the
// Railway UTC-vs-KST 9-15h day-boundary drift the audit surfaced.
//
// Contracts under test:
//   · TODAY_NEW  = count(oms_orders WHERE ordered_at >= KST midnight)
//   · PENDING    = count(oms_orders WHERE order_status IN [new, confirmed,
//                  processing, on_hold, ready_to_ship])
//   · Count unit = order headers, NEVER items (naive join multiplies).
//   · UNKNOWN ≠ ZERO: independent try/catch per metric — one failure MUST
//     NOT erase the other's known value.
//   · OPS-BRIEF-1A exception counters + SKU drill-down UNTOUCHED.

function mkOmsOrder(id, opts = {}) {
  return {
    id,
    channel:        opts.channel ?? 'ebay',
    external_order_id: opts.external_order_id ?? `EXT-${id}`,
    order_status:   opts.order_status ?? 'new',
    fulfillment_status: opts.fulfillment_status ?? 'unfulfilled',
    payment_status: opts.payment_status ?? 'paid',
    ordered_at:     opts.ordered_at ?? new Date().toISOString(),
    imported_at:    opts.imported_at ?? opts.ordered_at ?? new Date().toISOString(),
    created_at:     opts.created_at ?? new Date().toISOString(),
    cancelled_at:   opts.cancelled_at ?? null,
    shipped_at:     opts.shipped_at ?? null,
  };
}

test('OMS-T1 · summarizeOrders queries oms_orders, not wms_orders', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  const start = src.indexOf('async function summarizeOrders');
  const body  = src.slice(start, src.indexOf('\nasync function ', start));
  //   TODAY_NEW / PENDING block MUST NOT touch wms_orders.
  //   (The exception block below is UNCHANGED — it never touched wms_orders.)
  assert.equal(/from\(\s*['"]wms_orders['"]/.test(body), false,
    'summarizeOrders MUST NOT read from wms_orders');
  //   Must delegate to the OMS helper module (source of truth for TODAY_NEW / PENDING).
  assert.ok(/countTodayNew\(/.test(body),  'summarizeOrders must call countTodayNew helper');
  assert.ok(/countPendingAction\(/.test(body), 'summarizeOrders must call countPendingAction helper');
});

test('OMS-T2 · count unit is oms_orders headers, never items (5 orders + 12 items → 5)', async () => {
  restoreOriginals();
  const orders = [];
  for (let i = 1; i <= 5; i++) orders.push(mkOmsOrder(i, {
    order_status: 'new',
    ordered_at:  new Date(Date.now() + 60_000).toISOString(),   // ensure >= today
  }));
  // 12 items across those orders — a naive join would multiply the count.
  const items = [];
  for (let oid = 1; oid <= 5; oid++) {
    for (let j = 0; j < (oid === 1 ? 4 : 2); j++) {
      items.push({ id: items.length + 1, order_id: oid, external_line_id: `${oid}-${j}`, quantity: 1 });
    }
  }
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders, oms_order_items: items });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, 5,
    'TODAY_NEW must count order headers (5), not items (12)');
  assert.equal(b.orders.pending, 5, 'PENDING must count headers only');
});

test('OMS-T3 · KST day boundary independent of host TZ (15:30 UTC → 09-07 KST)', () => {
  restoreOriginals();
  const { getKstDateContext } = require(
    require.resolve('../../src/services/oms/omsBriefingCounts')
  );
  //   Frozen UTC instant equivalent to 2026-09-07 00:30 KST — inside "today"
  //   for Korean business day, ~9h ahead of UTC midnight.
  const ctx = getKstDateContext(new Date('2026-09-06T15:30:00Z'));
  assert.equal(ctx.dateStr,       '2026-09-07',
    'KST business date at 15:30 UTC must be 2026-09-07 (not the UTC-day 09-06)');
  assert.equal(ctx.todayStartIso, '2026-09-06T15:00:00.000Z',
    'todayStartIso must equal the UTC instant of KST 09-07 00:00:00+09:00');
});

test('OMS-T4 · late ingestion (ordered yesterday KST, imported today) excluded from TODAY_NEW', async () => {
  restoreOriginals();
  const { getKstDateContext } = require(
    require.resolve('../../src/services/oms/omsBriefingCounts')
  );
  const { todayStartIso } = getKstDateContext();
  const yesterdayKst = new Date(new Date(todayStartIso).getTime() - 86400_000).toISOString();

  const orders = [
    mkOmsOrder(1, { ordered_at: yesterdayKst,             imported_at: new Date().toISOString(), order_status: 'new' }), // late
    mkOmsOrder(2, { ordered_at: new Date().toISOString(), imported_at: new Date().toISOString(), order_status: 'new' }), // today
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, 1,
    'late-ingested yesterday-KST order MUST be excluded from TODAY_NEW (business date semantics)');
});

test('OMS-T5 · PENDING_ACTION set — includes new/confirmed/processing/on_hold/ready_to_ship, excludes shipped/completed/cancelled/returned', async () => {
  restoreOriginals();
  const orders = [
    mkOmsOrder(1, { order_status: 'new' }),
    mkOmsOrder(2, { order_status: 'confirmed' }),
    mkOmsOrder(3, { order_status: 'processing' }),
    mkOmsOrder(4, { order_status: 'on_hold' }),
    mkOmsOrder(5, { order_status: 'ready_to_ship' }),
    mkOmsOrder(6, { order_status: 'shipped' }),      // excluded
    mkOmsOrder(7, { order_status: 'completed' }),    // excluded
    mkOmsOrder(8, { order_status: 'cancelled' }),    // excluded
    mkOmsOrder(9, { order_status: 'returned' }),     // excluded
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.pending, 5,
    'PENDING must equal exactly the 5 actionable statuses — not the 4 terminal ones');
});

test('OMS-T5b · PENDING_ACTION_STATUSES constant is frozen literal set', () => {
  const { PENDING_ACTION_STATUSES } = require(
    require.resolve('../../src/services/oms/omsBriefingCounts')
  );
  assert.ok(Object.isFrozen(PENDING_ACTION_STATUSES),
    'PENDING_ACTION_STATUSES must be Object.freeze()d — future OMS console API MUST reuse the same literal to preserve count = detail');
  assert.deepEqual(PENDING_ACTION_STATUSES.slice(),
    ['new', 'confirmed', 'processing', 'on_hold', 'ready_to_ship']);
});

test('OMS-T6 · cancelled order placed today → in TODAY_NEW, not in PENDING', async () => {
  restoreOriginals();
  const now = new Date().toISOString();
  const orders = [
    mkOmsOrder(1, { order_status: 'cancelled', ordered_at: now, cancelled_at: now }),
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, 1,
    'cancelled-today order MUST count toward business-volume TODAY_NEW');
  assert.equal(b.orders.pending, 0,
    'cancelled order MUST NOT count as PENDING_ACTION (separate actionable-work truth)');
});

test('OMS-T7A · TODAY_NEW query fails / PENDING succeeds → total_today=null, pending known', async () => {
  const orders = [mkOmsOrder(1, { order_status: 'new' })];
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders });
  // Poison ONLY the .gte('ordered_at', ...) TODAY_NEW query.
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'oms_orders') return orig(name);
    // Two calls per invocation: TODAY_NEW (uses .gte) and PENDING (uses .in).
    // Return a chainable that inspects which one is being built.
    const state = { hasGte: false, hasIn: false };
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      gte() { state.hasGte = true; return chain; },
      in()  { state.hasIn  = true; return chain; },
      then(ok, err) {
        if (state.hasGte) return Promise.reject(new Error('simulated TODAY_NEW failure')).catch(err);
        // PENDING path — return the real count via orig().
        return orig('oms_orders').select('id', { count:'exact', head:true })
          .in('order_status', ['new','confirmed','processing','on_hold','ready_to_ship']).then(ok, err);
      },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, null, 'TODAY_NEW failure must leave total_today=null');
  assert.equal(b.orders.pending, 1, 'PENDING must remain known (independent failure handling)');
});

test('OMS-T7B · PENDING fails / TODAY_NEW succeeds → pending=null, total_today known', async () => {
  const orders = [mkOmsOrder(1, { order_status: 'new', ordered_at: new Date(Date.now()+60_000).toISOString() })];
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: orders });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'oms_orders') return orig(name);
    const state = { hasGte: false, hasIn: false };
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      gte() { state.hasGte = true; return chain; },
      in()  { state.hasIn  = true; return chain; },
      then(ok, err) {
        if (state.hasIn) return Promise.reject(new Error('simulated PENDING failure')).catch(err);
        // TODAY_NEW real path.
        return orig('oms_orders').select('id', { count:'exact', head:true })
          .gte('ordered_at', new Date(0).toISOString()).then(ok, err);
      },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.pending, null, 'PENDING failure must leave pending=null');
  assert.equal(b.orders.total_today, 1, 'TODAY_NEW must remain known (independent failure handling)');
});

test('OMS-T8 · no LIMIT-based count for OMS metrics (structural)', () => {
  const raw = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/oms/omsBriefingCounts.js'), 'utf8'
  );
  //   Strip comments so docstring text like ".limit(N)" describing the
  //   removed anti-pattern doesn't false-positive the check.
  const src = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  assert.equal(/\.limit\s*\(/.test(src), false,
    'omsBriefingCounts must not use .limit(...) — count: exact + head: true only');
  assert.ok(/count:\s*['"]exact['"]/.test(src) && /head:\s*true/.test(src),
    'omsBriefingCounts must use { count: "exact", head: true }');
});

test('OMS-T9 · KST dateStr used by summarizeTasks overdue boundary is KST-based', () => {
  //   getTodayBriefing derives dateStr from getKstDateContext and passes it to
  //   summarizeTasks (line ~64). We verify structurally that the getKstDateContext
  //   helper is the one producing dateStr consumed downstream — closing the
  //   Railway-UTC-vs-KST overdue drift for tasks in one go.
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  assert.ok(/getKstDateContext\(\)/.test(src),
    'operationsBriefing must derive its date context from getKstDateContext');
  assert.ok(/const\s*\{\s*dateStr\s*,\s*todayStartIso\s*\}\s*=\s*getKstDateContext/.test(src),
    'both dateStr and todayStartIso must come from the same KST-stable helper');
  //   Old process-local idiom must be gone.
  assert.equal(/new\s+Date\(\s*now\.getFullYear\(\)\s*,\s*now\.getMonth\(\)\s*,\s*now\.getDate\(\)/.test(src), false,
    'legacy process-local date construction must be removed');
});

test('OMS-T10 · OMS UNKNOWN visible in notification body · never silently normal', async () => {
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: [] });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'oms_orders') return orig(name);
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      gte() { return chain; }, in() { return chain; },
      then(_ok, err) { return Promise.reject(new Error('simulated OMS failure')).catch(err); },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, null);
  assert.equal(b.orders.pending, null);

  const n = opsBrief.buildBriefingNotification(b);
  assert.ok(/오늘 신규 주문 확인 실패/.test(n.body),
    'null total_today must produce explicit UNKNOWN wording in body');
  assert.ok(/미처리 주문 확인 실패/.test(n.body),
    'null pending must produce explicit UNKNOWN wording in body');
  assert.equal(/정상 운영/.test(n.body), false,
    '"정상 운영" MUST NOT appear when OMS counts are unknown');

  const rec = (b.recommendations || []).join('\n');
  assert.ok(/OMS 주문 카운트 확인 실패/.test(rec),
    'recommendations must include an OMS UNKNOWN entry when counts are null');
});

test('OMS-T11 · OPS-BRIEF-1A exception counters unchanged (regression fence)', async () => {
  restoreOriginals();
  const rows = [];
  let id = 1;
  for (let i = 0; i < 555; i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  for (let i = 0; i < 438; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, oms_orders: [] });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  //   Exact 1A/H1 truth must reproduce byte-for-byte in the 1B build.
  assert.equal(b.orders.exception_count,  993, 'exception_count unchanged (993)');
  assert.equal(b.orders.sku_match_failed, 555, 'sku_match_failed unchanged (555)');
});

test('OMS-T12 · SKU_MATCH_FAILED drill-down destination + params unchanged in 1B', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  //   skuDrill target must survive card-split unchanged.
  assert.ok(/page:\s*['"]exception-tasks['"]/.test(src));
  assert.ok(/params:\s*['"]exceptionType=SKU_MATCH_FAILED&status=open['"]/.test(src));
  assert.ok(/href:\s*['"][^'"]*page=exception-tasks[^'"]*exceptionType=SKU_MATCH_FAILED[^'"]*status=open['"]/.test(src));
  //   SKU 매칭 실패 row MUST still attach skuDrill (now inside the new 자동 예외 card).
  assert.ok(/SKU 매칭 실패[\s\S]{0,300}skuDrill/.test(src));
});

test('OMS-T13 · known OMS zero renders 0 in UI (not "-" · quiet-zero preserved)', async () => {
  restoreOriginals();
  //   Empty oms_orders → both counts return 0 (known). UI JSON shape must
  //   surface literal 0 numbers (not null · UNKNOWN reserved for query
  //   failure). Frontend opsBriefing.js already renders 0 as "0" and null
  //   as "-" via the sectionCard `value == null ? '-' : value` branch.
  const db = makeFakeDb({ wms_orders: [], team_tasks: [], oms_orders: [] });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.total_today, 0, 'empty OMS → total_today = 0 (KNOWN zero)');
  assert.equal(b.orders.pending, 0, 'empty OMS → pending = 0 (KNOWN zero)');
  assert.notEqual(b.orders.total_today, null, 'KNOWN zero must not be indistinguishable from UNKNOWN');
});

test('OMS-T14 · card composition split — 📦 주문 + ⚠️ 자동 예외 (no more "주문 (WMS)" or "주문 (OMS)")', () => {
  const raw = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  //   Strip comments so the "라벨: 주문 (OMS) 대신 주문" rationale line doesn't
  //   count as a UI exposure of the storage acronym.
  const src = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
  //   New card headers present in live code.
  assert.ok(/📦 주문['"]/.test(src),  'new 주문 card header present');
  assert.ok(/⚠️ 자동 예외['"]/.test(src), 'new 자동 예외 card header present');
  //   Legacy heterogeneous title gone from live code.
  assert.equal(/📦 주문 \(WMS\)/.test(src), false, 'legacy "주문 (WMS)" header must be removed');
  //   Owner rule §11: no storage acronym exposed in UI.
  assert.equal(/주문 \(OMS\)/.test(src), false, 'must not expose "OMS" storage acronym in UI');
});
