'use strict';

/**
 * tests/services/opsBriefingCountInvariant.test.js — OPS-BRIEF-1A.
 *
 * Owner-approved 2026-09-06.
 *
 * Root cause the fix addresses:
 *   src/services/operationsBriefing.js:summarizeOrders() previously
 *   counted `auto_generated=true AND status!=done` team_tasks via
 *   `.limit(500)` + in-memory `excRows.length`. Once open auto-exception
 *   cards exceeded 500 the metric saturated at exactly 500 while the UI
 *   label read "자동 예외 (전체)". Production observed: 993 real vs 500
 *   shown, 555 SKU_MATCH_FAILED real vs 296 shown (undercount from an
 *   arbitrary 500-row slice that happened to include only 296 matches).
 *
 * Invariant under test (owner rule §7 + §20):
 *   briefing.exception_count       == exact server-side count(auto_generated=true AND status!=done)
 *   briefing.sku_match_failed      == exact server-side count(... AND exception_type='SKU_MATCH_FAILED')
 *   briefing.sku_match_failed      == filtered detail array length from
 *                                     GET /api/tasks?autoGenerated=true&exceptionType=SKU_MATCH_FAILED&status=open
 *                                     (repo owner path)
 *
 * UNKNOWN ≠ ZERO (owner rule §5):
 *   If the count query fails, the metric MUST remain null (rendered as
 *   '-' in UI) — never silently collapse to 0.
 *
 * Non-scope:
 *   No production code was modified for testability. `src/api/ebayAPI.js`,
 *   tracking observer, scheduler code, and orderSync.js are untouched.
 *   R2-SHIP-6F1C-D deployment is independent.
 */

const test   = require('node:test');
const assert = require('node:assert/strict');
const fs     = require('fs');
const path   = require('path');

const SUPABASE_PATH   = require.resolve('../../src/db/supabaseClient');
const OPS_BRIEF_PATH  = require.resolve('../../src/services/operationsBriefing');
const REPO_PATH       = require.resolve('../../src/db/teamTaskRepository');

let _orig = null;
function saveOriginals() {
  _orig = {
    supabase: require.cache[SUPABASE_PATH],
    ops:      require.cache[OPS_BRIEF_PATH],
    repo:     require.cache[REPO_PATH],
  };
}
function restoreOriginals() {
  const restore = (p, orig) => {
    if (orig) require.cache[p] = orig;
    else      delete require.cache[p];
  };
  if (!_orig) return;
  restore(SUPABASE_PATH,  _orig.supabase);
  restore(OPS_BRIEF_PATH, _orig.ops);
  restore(REPO_PATH,      _orig.repo);
  _orig = null;
}

// ─────────────────────────────────────────────────────────────────────────
// Fake Supabase client — models the exact query shapes the code uses.
// ─────────────────────────────────────────────────────────────────────────
//
// Supported query shapes (only what our SUT calls):
//   from(table).select(cols, opts?).eq(k,v).neq(k,v)...  → thenable → {data,error}
//   from(table).select('id', { count:'exact', head:true }).eq/neq…  → thenable → {count,error}
//   from(table).select('*').eq/neq/in/or.order().limit().range()    → matches listTasks + summarizeOrders
//
// The stub applies filters conjunctively over a plain in-memory array of rows.
function makeFakeDb(tables) {
  // tables: { [tableName]: Row[] }
  function query(tableName) {
    const rows = Array.isArray(tables[tableName]) ? tables[tableName].slice() : [];
    const state = {
      filters: [],      // predicates: (row) => boolean
      countMode: null,  // 'exact' | null
      headOnly: false,
      selectCols: null,
      limitN: null,
      orderKey: null,
      orderAsc: true,
    };
    const applyFilters = () => rows.filter(r => state.filters.every(p => p(r)));

    const q = {
      select(cols, opts) {
        state.selectCols = cols;
        if (opts && opts.count) state.countMode = opts.count;
        if (opts && opts.head)  state.headOnly  = true;
        return q;
      },
      eq(k, v)  { state.filters.push(r => r[k] === v); return q; },
      neq(k, v) { state.filters.push(r => r[k] !== v); return q; },
      in(k, arr){ state.filters.push(r => arr.includes(r[k])); return q; },
      or(_expr) { /* summarizeOrders 등에서 사용 X — 미구현 pass-through */ return q; },
      order(k, opts) { state.orderKey = k; state.orderAsc = !(opts && opts.ascending === false); return q; },
      limit(n)  { state.limitN = n; return q; },
      range()   { return q; },
      // await 시 발화 — 결과 형태는 select 호출 시 옵션에 따라 결정.
      then(onFulfilled, onRejected) {
        try {
          const filtered = applyFilters();
          let out;
          if (state.countMode === 'exact' && state.headOnly) {
            // count-only response
            out = { data: null, count: filtered.length, error: null };
          } else {
            let ordered = filtered;
            if (state.orderKey) {
              ordered = filtered.slice().sort((a, b) => {
                const av = a[state.orderKey], bv = b[state.orderKey];
                if (av === bv) return 0;
                return (av < bv ? -1 : 1) * (state.orderAsc ? 1 : -1);
              });
            }
            const limited = state.limitN != null ? ordered.slice(0, state.limitN) : ordered;
            out = { data: limited, count: state.countMode === 'exact' ? filtered.length : null, error: null };
          }
          return Promise.resolve(out).then(onFulfilled, onRejected);
        } catch (e) {
          return Promise.reject(e).catch(onRejected);
        }
      },
    };
    return q;
  }

  return {
    from(tableName) {
      // Support both the direct-then and chainable await patterns.
      const q = query(tableName);
      return q;
    },
  };
}

function installFakeSupabase(fakeDb) {
  require.cache[SUPABASE_PATH] = {
    id: SUPABASE_PATH, filename: SUPABASE_PATH, loaded: true,
    exports: {
      getClient: () => fakeDb,
      isSupabaseEnabled: () => true,
      getDbSource: () => 'test',
      isDualWrite: () => false,
      withReadCache: async (fn) => ({ value: await fn(), stats: {} }),
    },
  };
  // Force operationsBriefing + repo to re-resolve the fake supabaseClient.
  delete require.cache[OPS_BRIEF_PATH];
  delete require.cache[REPO_PATH];
}

// Fixture builders ────────────────────────────────────────────────────────
function mkAutoExc(id, exceptionType, status = 'pending') {
  return {
    id,
    auto_generated: true,
    exception_type: exceptionType,
    status,
    created_at: new Date(Date.now() - id * 60_000).toISOString(),
    // populated to be listTasks-compatible
    title: `auto card #${id}`,
    priority: 'normal',
    created_by: null,
    completed_at: null,
    completion_note: null,
    memo: null,
    due_date: null,
    assignee_id: null,
    assignee_scope: 'operators',
    severity: 'medium',
    dedupe_key: `dedupe:${exceptionType}:${id}`,
    context: null,
    related_sku_id: null,
    related_order_id: null,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// STRUCTURAL — prove the LIMIT-500 saturation pattern is gone.
// ─────────────────────────────────────────────────────────────────────────

test('STRUCT-1 · summarizeOrders no longer uses .limit(500) on team_tasks', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  // Isolate the summarizeOrders function body (up to the next `async function` decl).
  const start = src.indexOf('async function summarizeOrders');
  assert.ok(start > 0, 'summarizeOrders must exist');
  const rest = src.slice(start);
  const end = rest.indexOf('\nasync function ');
  const body = end > 0 ? rest.slice(0, end) : rest;

  // NO in-memory team_tasks limit-then-length saturation.
  assert.equal(
    /from\(\s*['"]team_tasks['"]\s*\)[\s\S]{0,400}\.limit\(\s*500\s*\)/.test(body),
    false,
    'team_tasks LIMIT 500 saturation pattern must be removed from summarizeOrders'
  );

  // Exact-count contract MUST be present.
  assert.ok(
    /count:\s*['"]exact['"][\s\S]{0,50}head:\s*true/.test(body)
    || /head:\s*true[\s\S]{0,50}count:\s*['"]exact['"]/.test(body),
    'summarizeOrders must use { count:"exact", head:true } for team_tasks counts'
  );
});

test('STRUCT-2 · summarizeOrders preserves both auto-exception predicates', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  // .eq('auto_generated', true) AND .neq('status', 'done') both present.
  assert.ok(/\.eq\(\s*['"]auto_generated['"]\s*,\s*true\s*\)/.test(src));
  assert.ok(/\.neq\(\s*['"]status['"]\s*,\s*['"]done['"]\s*\)/.test(src));
  // SKU_MATCH_FAILED equality still expressed literally.
  assert.ok(/['"]SKU_MATCH_FAILED['"]/.test(src));
});

test('STRUCT-3 · UNKNOWN != ZERO — nulls not zero on catch path', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/services/operationsBriefing.js'), 'utf8'
  );
  const start = src.indexOf('async function summarizeOrders');
  const body  = src.slice(start, src.indexOf('\nasync function ', start));
  // Neither counter is initialised to 0 anymore.
  assert.equal(/let\s+exception_count\s*=\s*0\b/.test(body), false);
  assert.equal(/let\s+sku_match_failed\s*=\s*0\b/.test(body), false);
  // Both start life as null (UNKNOWN).
  assert.ok(/let\s+exception_count\s*=\s*null\b/.test(body));
  assert.ok(/let\s+sku_match_failed\s*=\s*null\b/.test(body));
});

test('STRUCT-4 · repo listTasks accepts exceptionType + status=open', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/db/teamTaskRepository.js'), 'utf8'
  );
  assert.ok(/function\s+listTasks\s*\(\s*\{[^}]*exceptionType[^}]*\}/.test(src),
    'listTasks signature must include exceptionType');
  assert.ok(/status\s*===\s*['"]open['"]/.test(src),
    'listTasks must branch on status === "open"');
  assert.ok(/\.eq\(\s*['"]exception_type['"]\s*,\s*exceptionType\s*\)/.test(src),
    'listTasks must forward exceptionType to a server-side .eq predicate');
});

test('STRUCT-5 · /api/tasks route whitelists exceptionType', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../src/web/routes/tasks.js'), 'utf8'
  );
  assert.ok(/ALLOWED_EXCEPTION_TYPES\s*=\s*\[\s*['"]SKU_MATCH_FAILED['"]\s*\]/.test(src),
    'tasks.js must declare a whitelist containing SKU_MATCH_FAILED');
  assert.ok(/invalid\s+exceptionType/i.test(src),
    'tasks.js must reject unsupported exceptionType with a 400 error message');
});

// ─────────────────────────────────────────────────────────────────────────
// BEHAVIORAL — exact counts + count = detail invariant.
// ─────────────────────────────────────────────────────────────────────────

test.beforeEach(saveOriginals);
test.afterEach(restoreOriginals);

test('BRIEF-T1 · >500 open auto exceptions counted exactly (505, not 500)', async () => {
  const rows = [];
  for (let i = 1; i <= 505; i++) rows.push(mkAutoExc(i, 'AUTOMATION_FAILED'));
  const db = makeFakeDb({
    wms_orders: [],
    team_tasks: rows,
  });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count, 505, 'must be exact 505, not saturated 500');
  assert.equal(b.orders.sku_match_failed, 0, 'no SKU_MATCH_FAILED in fixture → 0');
});

test('BRIEF-T2 · mixed 993 open · 555 SKU_MATCH_FAILED · reproduces production truth', async () => {
  const rows = [];
  let id = 1;
  for (let i = 0; i < 555; i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  for (let i = 0; i < 438; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  // 993 total, all pending
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  993, 'exact 993, not saturated 500');
  assert.equal(b.orders.sku_match_failed, 555, 'exact 555, not undercounted 296');
});

test('BRIEF-T3 · done SKU_MATCH_FAILED cards excluded from both open counts', async () => {
  const rows = [
    mkAutoExc(1, 'SKU_MATCH_FAILED', 'pending'),
    mkAutoExc(2, 'SKU_MATCH_FAILED', 'in_progress'),
    mkAutoExc(3, 'SKU_MATCH_FAILED', 'done'),       // must be excluded
    mkAutoExc(4, 'AUTOMATION_FAILED', 'done'),      // must be excluded
    mkAutoExc(5, 'AUTOMATION_FAILED', 'pending'),
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);

  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  3, 'done cards excluded → 3 open');
  assert.equal(b.orders.sku_match_failed, 2, 'done SKU cards excluded → 2 open');
});

test('BRIEF-T4/T7 · detail total = briefing sku_match_failed · count == detail', async () => {
  // Same 993/555 fixture — exercise both the service count and the repo owner-path
  // list under the same DB state.
  const rows = [];
  let id = 1;
  for (let i = 0; i < 555; i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  for (let i = 0; i < 438; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);

  const opsBrief = require(OPS_BRIEF_PATH);
  const repo     = require(REPO_PATH);

  const b = await opsBrief.getTodayBriefing();
  const detail = await repo.listTasks({
    user:          { id: 999, isAdmin: true },
    autoGenerated: 'true',
    exceptionType: 'SKU_MATCH_FAILED',
    status:        'open',
  });
  assert.equal(detail.length, b.orders.sku_match_failed,
    'briefing.sku_match_failed must equal filtered detail array length (count = detail invariant)');
  assert.equal(detail.length, 555, 'detail must return the full filtered set — not a page slice');
});

test('BRIEF-T5 · repo listTasks with unsupported exceptionType is caller-controlled', async () => {
  // The whitelist enforcement lives in the route layer (see STRUCT-5). The repo
  // itself must forward whatever value the caller passes as a .eq filter — this
  // preserves the count = detail contract without hard-coding the enum inside the
  // repo (extensible when new values are approved).
  const rows = [
    mkAutoExc(1, 'SKU_MATCH_FAILED'),
    mkAutoExc(2, 'NOT_ON_WHITELIST'),
  ];
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);
  const repo = require(REPO_PATH);
  const detail = await repo.listTasks({
    user: { id: 1, isAdmin: true }, autoGenerated: 'true', exceptionType: 'NOT_ON_WHITELIST',
  });
  assert.equal(detail.length, 1, 'repo forwards filter server-side; whitelist enforced upstream');
});

test('BRIEF-T6 · exceptionType filter runs server-side (not client-slice)', async () => {
  // 600 rows total; 55 match SKU_MATCH_FAILED. If filter ran client-side over a
  // capped 500-row slice, matches would be at most 55 * (500/600) ~ 45 on average
  // (or exactly 55 if the slice ordering happened to include all — the flaky
  // saturation bug we're removing). Server-side filter always returns 55.
  const rows = [];
  let id = 1;
  for (let i = 0; i < 545; i++) rows.push(mkAutoExc(id++, 'LANDING_COST_DATA_MISSING'));
  for (let i = 0; i < 55;  i++) rows.push(mkAutoExc(id++, 'SKU_MATCH_FAILED'));
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows, team_task_recipients: [] });
  installFakeSupabase(db);
  const repo = require(REPO_PATH);
  const detail = await repo.listTasks({
    user: { id: 1, isAdmin: true }, autoGenerated: 'true',
    exceptionType: 'SKU_MATCH_FAILED', status: 'open',
  });
  assert.equal(detail.length, 55, 'server-side filter reaches every matching row regardless of physical position');
});

test('BRIEF-UNKNOWN · count query failure leaves nulls, not zero', async () => {
  const rows = [mkAutoExc(1, 'SKU_MATCH_FAILED')];
  // Poison team_tasks count queries to force the catch branch.
  const db = makeFakeDb({ wms_orders: [], team_tasks: rows });
  const orig = db.from.bind(db);
  db.from = (name) => {
    if (name !== 'team_tasks') return orig(name);
    // Return a chainable stub that rejects on await.
    const chain = {
      select() { return chain; }, eq() { return chain; }, neq() { return chain; },
      order() { return chain; }, limit() { return chain; },
      then(_ok, err) { return Promise.reject(new Error('simulated count failure')).catch(err); },
    };
    return chain;
  };
  installFakeSupabase(db);
  const opsBrief = require(OPS_BRIEF_PATH);
  const b = await opsBrief.getTodayBriefing();
  assert.equal(b.orders.exception_count,  null, 'UNKNOWN != ZERO — must stay null');
  assert.equal(b.orders.sku_match_failed, null, 'UNKNOWN != ZERO — must stay null');
});

// ─────────────────────────────────────────────────────────────────────────
// Frontend structural tests (no jsdom infra in this repo) — cover T8..T12.
// ─────────────────────────────────────────────────────────────────────────

test('BRIEF-T8 · opsBriefing.js — SKU 매칭 실패 row carries drill target', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  // The literal tuple slot for SKU_MATCH_FAILED must reference the drill object.
  assert.ok(/SKU 매칭 실패[\s\S]{0,300}skuDrill/.test(src),
    'SKU 매칭 실패 items entry must attach the skuDrill target');
  // Drill target destination + params must match the deep-link contract.
  assert.ok(/exceptionType=SKU_MATCH_FAILED/.test(src));
  assert.ok(/status=open/.test(src));
  assert.ok(/page:\s*['"]exception-tasks['"]/.test(src));
});

test('BRIEF-T9 · opsBriefing.js — non-positive value renders as static row', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  // Guard: link renders ONLY when drill && numeric value > 0.
  assert.ok(/isNumericPositive[\s\S]{0,100}drill\s*&&\s*isNumericPositive/.test(src)
         || /drill\s*&&\s*isNumericPositive/.test(src),
    'row link must guard on (drill && numeric value > 0) — zero / null renders as non-clickable');
});

test('BRIEF-T10 · exceptionFilter.js — first fetch sends URL exceptionType', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  // URL parse present, whitelist enforced, and refresh() sends exceptionType server-side.
  assert.ok(/URL_ALLOWED_EXCEPTION_TYPES[\s\S]{0,80}SKU_MATCH_FAILED/.test(src),
    'exceptionFilter must declare a URL whitelist');
  assert.ok(/URLSearchParams\(location\.search\)/.test(src),
    'exceptionFilter must parse location.search');
  assert.ok(/params\.set\(\s*['"]exceptionType['"]\s*,\s*urlExceptionType\s*\)/.test(src),
    'refresh() must forward urlExceptionType to the server');
});

test('BRIEF-T11 · exceptionFilter.js — status=open forwarded to server', () => {
  const src = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  assert.ok(/urlStatusOpen[\s\S]{0,120}params\.set\(\s*['"]status['"]\s*,\s*['"]open['"]\s*\)/.test(src),
    'urlStatusOpen must translate to server-side status=open on refresh()');
});

test('BRIEF-T12 · drill-down surface uses GET only — no mutation added', () => {
  const briefSrc = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/opsBriefing.js'), 'utf8'
  );
  const filterSrc = fs.readFileSync(
    path.resolve(__dirname, '../../public/js/exceptionFilter.js'), 'utf8'
  );
  // The new drill click path uses history.pushState + showPage. No fetch() with a
  // non-GET method was added by 1A.
  const drillBlock = briefSrc.slice(briefSrc.indexOf('ob-drill'));
  assert.equal(/method:\s*['"](POST|PATCH|PUT|DELETE)['"]/.test(drillBlock), false,
    'briefing drill wiring must be GET-only');
  // The URL-init path in exceptionFilter must not add any new mutation call —
  // PATCH /api/tasks/:id (완료 처리) already exists and is UNCHANGED.
  const patchCount = (filterSrc.match(/method:\s*['"]PATCH['"]/g) || []).length;
  assert.equal(patchCount, 1, 'exceptionFilter should still have exactly 1 PATCH call (existing 완료 처리 workflow — untouched)');
});
