/**
 * 업무 관리 API (/api/tasks, /api/tasks/stats)
 *
 * 권한:
 *   owner: 전체 조회/등록/수정/삭제. 수신자 상태 force-complete 가능.
 *   staff: 본인 recipient 있는 task만. 본인 상태만 변경.
 *
 * PATCH body:
 *   - 메타데이터 변경 (title/assigneeId/assigneeScope/dueDate/priority/memo) — admin only
 *   - 상태 변경 (status/completionNote/userId?) — recipient 기준
 *     - userId 생략 시 req.user.id (본인) 대상
 *     - userId 지정은 admin만 허용 (직원 대신 완료 처리)
 *
 * Phase 3 PR L-2 audit wiring:
 *   POST   /                  task_create
 *   PATCH  /:id (메타 분기)    task_update
 *   PATCH  /:id (상태 분기)    task_status_update
 *   POST   /:id/complete      task_status_update (multipart + 완료)
 *   DELETE /:id               task_delete
 *
 *   - audit 정책: pre-runAction strict (실패 시 500), post-updateRun best-effort.
 *   - validation 등 audit 생성 전 실패는 audit 기록 X.
 *   - snapshot 에는 핵심 필드만 — req.body 전체 / token / secret 일체 포함 금지.
 *   - 로그에는 actionName / id / executedBy / error.message 만.
 *   - rollback_method='manual' + 짧은 hint.
 */
const express = require('express');
const crypto = require('crypto');
const multer = require('multer');
const { requireAdmin } = require('../../middleware/auth');
const repo = require('../../db/teamTaskRepository');
const { notify, notifyMany, notifyAdmins, getStaffIds } = require('../../services/notificationService');
const sseHub = require('../../services/sseHub');
const { getClient } = require('../../db/supabaseClient');
const safetyExec = require('../../services/safetyExec');

// snapshot 압축용: 긴 텍스트를 max 500자로 자름 (raw body dump 방지)
function previewText(s, max = 500) {
  if (s == null) return null;
  const str = String(s);
  return str.length > max ? str.slice(0, max) + '…' : str;
}

// snapshot 표준화 — task row → 핵심 필드만
function taskSnapshot(t) {
  if (!t) return null;
  return {
    id:             t.id,
    title:          previewText(t.title, 500),
    status:         t.status,
    priority:       t.priority,
    assignee_id:    t.assignee_id,
    assignee_scope: t.assignee_scope,
    due_date:       t.due_date,
    updated_at:     t.updated_at,
  };
}

const router = express.Router();

const ATTACHMENT_BUCKET = 'task-attachments';
const MAX_FILES_PER_COMPLETE = 5;
const MAX_FILE_BYTES = 10 * 1024 * 1024;
const ALLOWED_MIME = new Set([
  'application/pdf',
  'image/jpeg', 'image/png', 'image/webp',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // xlsx
  'application/vnd.ms-excel', // xls
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // docx
  'application/msword', // doc
  'application/zip', 'application/x-zip-compressed',
]);

const uploadAttachments = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_FILE_BYTES, files: MAX_FILES_PER_COMPLETE },
  fileFilter: (_req, file, cb) => {
    if (ALLOWED_MIME.has(file.mimetype)) return cb(null, true);
    cb(new Error(`허용되지 않는 파일 형식: ${file.mimetype}`));
  },
});

function sanitizeFileName(name) {
  return (name || 'file')
    .replace(/[\\/\x00-\x1f]/g, '_')
    .slice(0, 150);
}

// GET /api/tasks
//   query autoGenerated:
//     undefined / 'false' (default) → 사람 카드만 (기존 직원 화면 보호)
//     'true'                        → 자동 예외 카드만 (admin 전용 자동 예외 탭)
//     'all'                         → 모두
router.get('/', async (req, res) => {
  try {
    const { status, scope, assigneeId, autoGenerated } = req.query;
    const data = await repo.listTasks({
      user: req.user,
      status,
      scope,
      assigneeId: assigneeId ? parseInt(assigneeId, 10) : undefined,
      autoGenerated,
    });
    res.json({ data });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// GET /api/tasks/stats?scope=mine|all&autoGenerated=false|true|all
//   scope=mine (default)         — 호출한 사장이 직접 지시한 업무만 집계
//   scope=all                    — 모든 owner 의 업무 합계
//   autoGenerated=false (default) — 사람 카드만 (기존 위젯 의미 유지)
//   autoGenerated=true            — 자동 예외 카드 통계만
//   autoGenerated=all             — 둘 다
router.get('/stats', requireAdmin, async (req, res) => {
  try {
    const scope = req.query.scope || 'mine';
    const ownerId = scope === 'all' ? undefined : req.user.id;
    const stats = await repo.getTodayStats({ ownerId, autoGenerated: req.query.autoGenerated });
    res.json(stats);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// POST /api/tasks (owner only)                                  [audit: task_create]
router.post('/', requireAdmin, async (req, res) => {
  // pre-validation (audit row 생성 전 — 실패 시 audit 기록 X)
  const { title, assigneeId, assigneeScope, dueDate, priority, memo } = req.body || {};
  if (!title || !title.trim()) return res.status(400).json({ error: '업무 내용을 입력하세요' });

  const scope = assigneeScope === 'all' ? 'all' : 'specific';
  const assignee = scope === 'all' ? null : (assigneeId ? parseInt(assigneeId, 10) : null);
  if (scope === 'specific' && !assignee) {
    return res.status(400).json({ error: '담당자를 선택하거나 전체 공지로 지정하세요' });
  }

  const executedBy = req.user.id;

  // pre-action audit (strict)
  let run;
  try {
    run = await safetyExec.runAction({
      actionName:       'task_create',
      executedBy,
      isLegacyExecutor: req.user?.isLegacy === true,
      targetTable:      'team_tasks',
      targetId:         null,             // post 에 채움
      beforeSnapshot:   null,             // CREATE
      rollbackMethod:   'manual',
      rollbackHint:     '생성된 team_tasks row 를 확인 후 close/delete 정책에 따라 수동 처리하세요.',
      status: 'pending',
    });
  } catch (auditErr) {
    console.error('[tasks] runAction failed (task_create):', {
      actionName: 'task_create', executedBy, message: auditErr.message,
    });
    return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
  }

  try {
    const { task, recipientCount } = await repo.createTask({
      title: title.trim(),
      assignee_id: assignee,
      assignee_scope: scope,
      due_date: dueDate ? new Date(dueDate).toISOString() : null,
      priority: priority === 'urgent' ? 'urgent' : 'normal',
      memo: memo?.trim() || null,
      created_by: executedBy,
    });

    // 알림 (DB) + SSE 실시간 이벤트
    const ssePayload = {
      type: 'task_assigned',
      taskId: task.id,
      title: task.title,
      priority: task.priority,
      urgent: task.priority === 'urgent',
      scope,
      linkUrl: '/?page=tasks',
    };

    if (scope === 'specific' && assignee && assignee !== executedBy) {
      await notify({
        recipientId: assignee,
        type: 'task_assigned',
        title: priority === 'urgent' ? '[긴급] 새 업무 지시' : '새 업무 지시',
        body: task.title,
        linkUrl: '/?page=tasks',
        relatedType: 'task',
        relatedId: task.id,
      });
      sseHub.sendTo(assignee, ssePayload);
    } else if (scope === 'all') {
      const staffIds = await getStaffIds();
      await notifyMany(staffIds, {
        type: 'task_assigned',
        title: '전체 공지 업무',
        body: task.title,
        linkUrl: '/?page=tasks',
        relatedType: 'task',
        relatedId: task.id,
      });
      sseHub.sendToMany(staffIds, ssePayload);
    }

    // post-action audit (best-effort) — 핵심 필드만
    safetyExec.updateRun(run.id, {
      status:        'succeeded',
      targetId:      task.id,
      afterSnapshot: { ...taskSnapshot(task), recipient_count: recipientCount },
    });

    res.json({ data: task, recipientCount });
  } catch (e) {
    safetyExec.updateRun(run.id, { status: 'failed', errorCode: 'unknown', errorMessage: e.message });
    res.status(500).json({ error: e.message });
  }
});

// PATCH /api/tasks/:id
// 2가지 모드 자동 분기:
//   메타 필드 (title/due/priority/memo/assigneeId/assigneeScope) → admin만, team_tasks update  [audit: task_update]
//   status/completionNote → recipient 업데이트                                                  [audit: task_status_update]
// 두 분기가 동시 발생하면 audit row 2건 생성.
router.patch('/:id', async (req, res) => {
  // pre-validation (audit row 생성 전)
  const id = parseInt(req.params.id, 10);
  if (!Number.isFinite(id)) return res.status(400).json({ error: 'invalid id' });

  const task = await repo.getTask(id).catch((e) => { throw e; });
  if (!task) return res.status(404).json({ error: '업무를 찾을 수 없습니다' });

  const body = req.body || {};
  const isMetaUpdate = body.title !== undefined || body.assigneeScope !== undefined ||
                       body.assigneeId !== undefined || body.dueDate !== undefined ||
                       body.priority !== undefined || body.memo !== undefined;
  const isStatusUpdate = body.status !== undefined || body.completionNote !== undefined;

  const executedBy = req.user.id;

  // ── 메타 업데이트 ──                                              [audit: task_update]
  if (isMetaUpdate) {
    if (!req.user.isAdmin) return res.status(403).json({ error: '메타데이터 수정은 사장만 가능합니다' });
    const metaUpdates = {};
    if (body.title !== undefined) metaUpdates.title = body.title.trim();
    if (body.dueDate !== undefined) metaUpdates.due_date = body.dueDate ? new Date(body.dueDate).toISOString() : null;
    if (body.priority !== undefined) metaUpdates.priority = body.priority;
    if (body.memo !== undefined) metaUpdates.memo = body.memo?.trim() || null;
    // assignee 재배정은 지금은 비활성 (recipient 재구성 필요 — 추후)
    if (Object.keys(metaUpdates).length === 0 && !isStatusUpdate) {
      return res.status(400).json({ error: '변경할 내용이 없습니다' });
    }
    if (Object.keys(metaUpdates).length > 0) {
      let metaRun;
      try {
        metaRun = await safetyExec.runAction({
          actionName:       'task_update',
          executedBy,
          isLegacyExecutor: req.user?.isLegacy === true,
          targetTable:      'team_tasks',
          targetId:         id,
          beforeSnapshot:   taskSnapshot(task),
          relatedTaskId:    id,
          rollbackMethod:   'manual',
          rollbackHint:     'input_snapshot 을 참고해 team_tasks row 를 수동 복구하세요.',
          status: 'pending',
        });
      } catch (auditErr) {
        console.error('[tasks] runAction failed (task_update):', {
          actionName: 'task_update', id, executedBy, message: auditErr.message,
        });
        return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
      }
      try {
        await repo.updateTaskMeta(id, metaUpdates);
        const refreshed = await repo.getTask(id);
        safetyExec.updateRun(metaRun.id, { status: 'succeeded', afterSnapshot: taskSnapshot(refreshed) });
      } catch (e) {
        safetyExec.updateRun(metaRun.id, { status: 'failed', errorCode: 'unknown', errorMessage: e.message });
        return res.status(500).json({ error: e.message });
      }
    }
  }

  // ── 상태 업데이트 (recipient 기준) ──                             [audit: task_status_update]
  if (isStatusUpdate) {
    const targetUserId = req.user.isAdmin && body.userId ? parseInt(body.userId, 10) : req.user.id;

    // 본인이 아닌 recipient 대상은 admin만 가능
    if (targetUserId !== req.user.id && !req.user.isAdmin) {
      return res.status(403).json({ error: '타인 상태 변경은 사장만 가능합니다' });
    }

    // recipient 존재 확인
    const rec = await repo.getRecipient(id, targetUserId);
    if (!rec) return res.status(404).json({ error: '해당 직원의 업무 수신 기록이 없습니다' });

    // 상태 validation (PR T-1: 'blocked' 추가)
    const newStatus = body.status;
    if (newStatus !== undefined && !['pending', 'in_progress', 'done', 'blocked'].includes(newStatus)) {
      return res.status(400).json({ error: '올바른 상태가 아닙니다' });
    }

    // done인데 본인 완료 + 사장 아님 → 코멘트 필수
    if (newStatus === 'done' && targetUserId === req.user.id && !req.user.isAdmin) {
      const note = body.completionNote;
      if (!note || !String(note).trim()) {
        return res.status(400).json({ error: '완료 코멘트를 입력하세요' });
      }
    }

    let statusRun;
    try {
      statusRun = await safetyExec.runAction({
        actionName:       'task_status_update',
        executedBy,
        isLegacyExecutor: req.user?.isLegacy === true,
        targetTable:      'team_tasks',
        targetId:         id,
        beforeSnapshot:   {
          ...taskSnapshot(task),
          recipient_user_id: targetUserId,
          recipient_status:  rec.status,
        },
        relatedTaskId:    id,
        rollbackMethod:   'manual',
        rollbackHint:     'input_snapshot 을 참고해 team_tasks / team_task_recipients row 를 수동 복구하세요.',
        status: 'pending',
      });
    } catch (auditErr) {
      console.error('[tasks] runAction failed (task_status_update):', {
        actionName: 'task_status_update', id, executedBy, message: auditErr.message,
      });
      return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
    }

    try {
      await repo.updateRecipient(id, targetUserId, {
        status: newStatus,
        completionNote: body.completionNote !== undefined ? (body.completionNote?.trim() || null) : undefined,
      });

      // 직원이 본인 완료 → 사장에게 알림
      if (newStatus === 'done' && !req.user.isAdmin) {
        await notifyAdmins({
          type: 'task_completed',
          title: `${req.user.displayName} 업무 완료`,
          body: `${task.title}${body.completionNote ? ' — ' + body.completionNote : ''}`,
          linkUrl: '/?page=tasks',
          relatedType: 'task',
          relatedId: id,
        });
      }

      const refreshed = await repo.getTask(id);
      safetyExec.updateRun(statusRun.id, {
        status: 'succeeded',
        afterSnapshot: {
          ...taskSnapshot(refreshed),
          recipient_user_id: targetUserId,
          recipient_status:  newStatus !== undefined ? newStatus : rec.status,
        },
      });
    } catch (e) {
      safetyExec.updateRun(statusRun.id, { status: 'failed', errorCode: 'unknown', errorMessage: e.message });
      return res.status(500).json({ error: e.message });
    }
  }

  try {
    const updated = await repo.getTask(id);
    res.json({ data: updated });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// POST /api/tasks/:id/complete — 본인 완료 + 파일 첨부 (multipart)   [audit: task_status_update]
// 필드: completionNote(text, 직원 필수), files[]
router.post('/:id/complete', (req, res, next) => {
  uploadAttachments.array('files', MAX_FILES_PER_COMPLETE)(req, res, (err) => {
    if (err) {
      const msg = err.code === 'LIMIT_FILE_SIZE'
        ? `파일이 너무 큽니다 (최대 ${MAX_FILE_BYTES / 1024 / 1024}MB)`
        : err.code === 'LIMIT_FILE_COUNT'
        ? `파일이 너무 많습니다 (최대 ${MAX_FILES_PER_COMPLETE}개)`
        : err.message || '업로드 오류';
      return res.status(400).json({ error: msg });
    }
    next();
  });
}, async (req, res) => {
  const taskId = parseInt(req.params.id, 10);
  const files = req.files || [];
  const uploadedPaths = [];

  // pre-validation (audit row 생성 전)
  if (!Number.isFinite(taskId)) return res.status(400).json({ error: 'invalid id' });

  let task, rec, note, existingCount;
  try {
    task = await repo.getTask(taskId);
    if (!task) return res.status(404).json({ error: '업무를 찾을 수 없습니다' });

    const targetUserId = req.user.id;
    rec = await repo.getRecipient(taskId, targetUserId);
    if (!rec) return res.status(404).json({ error: '해당 업무의 수신자가 아닙니다' });

    note = (req.body?.completionNote || '').trim();
    if (!req.user.isAdmin && !note) {
      return res.status(400).json({ error: '완료 코멘트를 입력하세요' });
    }

    existingCount = await repo.countAttachmentsForUser(taskId, targetUserId);
    if (existingCount + files.length > MAX_FILES_PER_COMPLETE) {
      return res.status(400).json({ error: `업무당 최대 ${MAX_FILES_PER_COMPLETE}개까지 첨부 가능합니다 (현재 ${existingCount}개)` });
    }
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }

  const targetUserId = req.user.id;
  const executedBy = req.user.id;

  // pre-action audit (strict)
  let run;
  try {
    run = await safetyExec.runAction({
      actionName:       'task_status_update',
      executedBy,
      isLegacyExecutor: req.user?.isLegacy === true,
      targetTable:      'team_tasks',
      targetId:         taskId,
      beforeSnapshot:   {
        ...taskSnapshot(task),
        recipient_user_id: targetUserId,
        recipient_status:  rec.status,
      },
      relatedTaskId:    taskId,
      rollbackMethod:   'manual',
      rollbackHint:
        'input_snapshot 을 참고해 team_tasks / team_task_recipients / team_task_attachments row 를 수동 복구하세요.',
      status: 'pending',
    });
  } catch (auditErr) {
    console.error('[tasks] runAction failed (task_status_update via complete):', {
      actionName: 'task_status_update', id: taskId, executedBy, message: auditErr.message,
    });
    return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
  }

  try {
    const storage = getClient().storage.from(ATTACHMENT_BUCKET);

    for (const f of files) {
      const rand = crypto.randomBytes(6).toString('hex');
      const clean = sanitizeFileName(f.originalname);
      const path = `${taskId}/${targetUserId}/${Date.now()}-${rand}-${clean}`;
      const { error: upErr } = await storage.upload(path, f.buffer, {
        contentType: f.mimetype,
        upsert: false,
      });
      if (upErr) throw new Error(`Storage 업로드 실패: ${upErr.message}`);
      uploadedPaths.push(path);
      await repo.addAttachment({
        taskId,
        userId: targetUserId,
        filePath: path,
        fileName: clean,
        mimeType: f.mimetype,
        sizeBytes: f.size,
      });
    }

    await repo.updateRecipient(taskId, targetUserId, {
      status: 'done',
      completionNote: note || rec.completion_note || null,
    });

    if (!req.user.isAdmin) {
      await notifyAdmins({
        type: 'task_completed',
        title: `${req.user.displayName} 업무 완료`,
        body: `${task.title}${note ? ' — ' + note : ''}${files.length ? ` (📎 ${files.length})` : ''}`,
        linkUrl: '/?page=tasks',
        relatedType: 'task',
        relatedId: taskId,
      });
    }

    const updated = await repo.getTask(taskId);
    safetyExec.updateRun(run.id, {
      status: 'succeeded',
      afterSnapshot: {
        ...taskSnapshot(updated),
        recipient_user_id: targetUserId,
        recipient_status:  'done',
        attachments_added: files.length,
      },
    });
    res.json({ data: updated, attachmentsAdded: files.length });
  } catch (e) {
    // rollback: delete any files uploaded in this request
    if (uploadedPaths.length > 0) {
      try { await getClient().storage.from(ATTACHMENT_BUCKET).remove(uploadedPaths); } catch {}
    }
    safetyExec.updateRun(run.id, { status: 'failed', errorCode: 'unknown', errorMessage: e.message });
    res.status(500).json({ error: e.message });
  }
});

// GET /api/tasks/:id/attachments/:attId/url — 서명 다운로드 URL 발급
router.get('/:id/attachments/:attId/url', async (req, res) => {
  try {
    const taskId = parseInt(req.params.id, 10);
    const attId = parseInt(req.params.attId, 10);
    const att = await repo.getAttachment(attId);
    if (!att || att.task_id !== taskId) return res.status(404).json({ error: '첨부를 찾을 수 없습니다' });

    if (!req.user.isAdmin && att.user_id !== req.user.id) {
      return res.status(403).json({ error: '권한이 없습니다' });
    }

    const { data, error } = await getClient().storage
      .from(ATTACHMENT_BUCKET)
      .createSignedUrl(att.file_path, 300, { download: att.file_name });
    if (error) throw error;
    res.json({ signedUrl: data.signedUrl, fileName: att.file_name });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

// POST /api/tasks/:id/blocked — 본인 recipient 막힘 보고 (한줄 사유)   [audit: task_status_update]
// PR T-1. body: { reason } — completion_note 컬럼 재사용 (status='blocked' 일 때 '막힘 사유' 의미).
router.post('/:id/blocked', async (req, res) => {
  const taskId = parseInt(req.params.id, 10);
  if (!Number.isFinite(taskId)) return res.status(400).json({ error: 'invalid id' });

  const reason = String(req.body?.reason || '').trim();
  if (!reason) return res.status(400).json({ error: '막힘 사유를 한줄로 입력하세요' });
  if (reason.length > 200) return res.status(400).json({ error: '막힘 사유는 200자 이내로 입력하세요' });

  let task, rec;
  try {
    task = await repo.getTask(taskId);
    if (!task) return res.status(404).json({ error: '업무를 찾을 수 없습니다' });

    rec = await repo.getRecipient(taskId, req.user.id);
    if (!rec) return res.status(404).json({ error: '해당 업무의 수신자가 아닙니다' });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }

  const executedBy = req.user.id;

  let run;
  try {
    run = await safetyExec.runAction({
      actionName:       'task_status_update',
      executedBy,
      isLegacyExecutor: req.user?.isLegacy === true,
      targetTable:      'team_tasks',
      targetId:         taskId,
      beforeSnapshot:   {
        ...taskSnapshot(task),
        recipient_user_id: req.user.id,
        recipient_status:  rec.status,
      },
      relatedTaskId:    taskId,
      rollbackMethod:   'manual',
      rollbackHint:
        'input_snapshot 의 recipient_status 로 team_task_recipients 를 되돌리세요.',
      status: 'pending',
    });
  } catch (auditErr) {
    console.error('[tasks] runAction failed (task_status_update via blocked):', {
      actionName: 'task_status_update', id: taskId, executedBy, message: auditErr.message,
    });
    return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
  }

  try {
    await repo.updateRecipient(taskId, req.user.id, {
      status: 'blocked',
      completionNote: reason,
    });

    if (!req.user.isAdmin) {
      await notifyAdmins({
        type: 'task_blocked',
        title: `${req.user.displayName} 업무 막힘`,
        body: `${task.title} — ${reason}`,
        linkUrl: '/?page=tasks',
        relatedType: 'task',
        relatedId: taskId,
      });
    }

    const updated = await repo.getTask(taskId);
    safetyExec.updateRun(run.id, {
      status: 'succeeded',
      afterSnapshot: {
        ...taskSnapshot(updated),
        recipient_user_id: req.user.id,
        recipient_status:  'blocked',
      },
    });
    res.json({ data: updated });
  } catch (e) {
    safetyExec.updateRun(run.id, { status: 'failed', errorCode: 'unknown', errorMessage: e.message });
    res.status(500).json({ error: e.message });
  }
});

// DELETE /api/tasks/:id (owner only) — CASCADE로 recipients 함께 삭제   [audit: task_delete]
router.delete('/:id', requireAdmin, async (req, res) => {
  // pre-validation
  const id = parseInt(req.params.id, 10);
  if (!Number.isFinite(id)) return res.status(400).json({ error: 'invalid id' });

  let existing;
  try {
    existing = await repo.getTask(id);
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
  if (!existing) return res.status(404).json({ error: '업무를 찾을 수 없습니다' });

  const executedBy = req.user.id;

  // pre-action audit (strict)
  let run;
  try {
    run = await safetyExec.runAction({
      actionName:       'task_delete',
      executedBy,
      isLegacyExecutor: req.user?.isLegacy === true,
      targetTable:      'team_tasks',
      targetId:         id,
      beforeSnapshot:   taskSnapshot(existing),
      relatedTaskId:    id,
      rollbackMethod:   'manual',
      rollbackHint:
        'input_snapshot 을 참고해 team_tasks row 를 INSERT 로 재생성하세요. CASCADE 로 함께 삭제된 recipients 도 별도 복구 필요.',
      status: 'pending',
    });
  } catch (auditErr) {
    console.error('[tasks] runAction failed (task_delete):', {
      actionName: 'task_delete', id, executedBy, message: auditErr.message,
    });
    return res.status(500).json({ error: 'audit 시스템 일시 장애 — 잠시 후 재시도' });
  }

  try {
    await repo.deleteTask(id);
    safetyExec.updateRun(run.id, {
      status:        'succeeded',
      afterSnapshot: { deleted: true, id },
    });
    res.json({ ok: true });
  } catch (e) {
    safetyExec.updateRun(run.id, { status: 'failed', errorCode: 'fk_violation_or_other', errorMessage: e.message });
    // FK 위반 (PostgreSQL 23503) 이면 사용자 친화적 메시지
    const msg = e.message || '';
    if (e.code === '23503' || /violates foreign key constraint|foreign key/i.test(msg)) {
      return res.status(409).json({
        error: '이 업무를 참조하는 다른 데이터가 있어 삭제할 수 없습니다 (' + (msg.match(/constraint "([^"]+)"/) || [, '확인 필요'])[1] + '). 관리자에게 마이그레이션 053 확인 요청.',
        code: 'FK_VIOLATION',
      });
    }
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
